"""baseline schema

Revision ID: 284216425e18
Revises: 
Create Date: 2026-05-26 19:33:29.376008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '284216425e18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregation_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('processed_rows', sa.BigInteger(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('departments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cost_center_code', sa.String(length=64), nullable=True),
    sa.Column('manager_user_id', sa.BigInteger(), nullable=True),
    sa.Column('monthly_budget_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cost_center_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lava_connections',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('available_models_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lava_runtime_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('providers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('employee_no', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_no')
    )
    op.create_foreign_key(
        'fk_departments_manager_user_id_users',
        'departments',
        'users',
        ['manager_user_id'],
        ['id'],
    )
    op.create_table('ai_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=False),
    sa.Column('product', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('monthly_cost_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('renewal_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scope_type', sa.String(length=64), nullable=True),
    sa.Column('scope_id', sa.BigInteger(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('encrypted_dek', sa.Text(), nullable=False),
    sa.Column('kms_key_id', sa.String(length=128), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('masked_key', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotation_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=False),
    sa.Column('request_type', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_imports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('requester_user_id', sa.BigInteger(), nullable=False),
    sa.Column('export_type', sa.String(length=64), nullable=False),
    sa.Column('filters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lava_task_bindings',
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('connection_id', sa.BigInteger(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['lava_connections.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('models',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('model_code', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('capabilities_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_code', name='uq_provider_model_code')
    )
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('usage_purposes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_usage_purpose_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_usage_purpose_code')
    )
    op.create_table('ai_account_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ai_account_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['ai_account_id'], ['ai_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_key_entitlements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('allowed_models_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('monthly_soft_limit_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('monthly_hard_limit_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_steps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('approver_user_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_role', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'step_no', name='uq_approval_request_step')
    )
    op.create_table('asset_contracts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=True),
    sa.Column('ai_account_id', sa.BigInteger(), nullable=True),
    sa.Column('billing_cycle', sa.String(length=32), nullable=False),
    sa.Column('monthly_fee_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('yearly_fee_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('monthly_amortized_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(billing_cycle = 'MONTHLY' AND monthly_fee_usd IS NOT NULL AND yearly_fee_usd IS NULL) OR (billing_cycle = 'YEARLY' AND yearly_fee_usd IS NOT NULL AND monthly_fee_usd IS NULL) OR (billing_cycle = 'USAGE_BASED' AND monthly_fee_usd IS NULL AND yearly_fee_usd IS NULL)", name='ck_asset_contract_fee_fields'),
    sa.CheckConstraint("billing_cycle IN ('MONTHLY','YEARLY','USAGE_BASED')", name='ck_asset_contract_billing_cycle'),
    sa.CheckConstraint('(api_key_id IS NOT NULL AND ai_account_id IS NULL) OR (api_key_id IS NULL AND ai_account_id IS NOT NULL)', name='ck_asset_contract_one_asset'),
    sa.CheckConstraint('end_date IS NULL OR end_date > start_date', name='ck_asset_contract_date_range'),
    sa.ForeignKeyConstraint(['ai_account_id'], ['ai_accounts.id'], ),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistant_conversations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('linked_approval_request_id', sa.BigInteger(), nullable=True),
    sa.Column('last_risk_level', sa.String(length=16), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','CLOSED')", name='ck_assistant_conversation_status'),
    sa.ForeignKeyConstraint(['linked_approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_id', name='uq_assistant_conversation_user_session')
    )
    op.create_index('ix_assistant_conversations_user_last_message_at', 'assistant_conversations', ['user_id', 'last_message_at'], unique=False)
    op.create_table('budget_reservations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reserved_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', name='uq_budget_reservation_request_id')
    )
    op.create_table('gateway_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('trace_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('provider_http_status', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('raw_response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', 'user_id', name='uq_gateway_idempotency_user'),
    sa.UniqueConstraint('request_id', name='uq_gateway_request_id')
    )
    op.create_table('model_prices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('input_price_per_1m', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('output_price_per_1m', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name='ck_model_price_period'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'effective_from', name='uq_model_price_effective_from')
    )
    op.create_table('project_budgets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('monthly_soft_limit_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('monthly_hard_limit_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name='ck_project_budget_period'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'effective_from', name='uq_project_budget_effective_from')
    )
    op.create_table('resource_limit_states',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=True),
    sa.Column('ai_account_id', sa.BigInteger(), nullable=True),
    sa.Column('tokens_5h', sa.BigInteger(), nullable=False),
    sa.Column('tokens_today', sa.BigInteger(), nullable=False),
    sa.Column('tokens_week', sa.BigInteger(), nullable=False),
    sa.Column('tokens_month', sa.BigInteger(), nullable=False),
    sa.Column('limit_5h', sa.BigInteger(), nullable=True),
    sa.Column('limit_day', sa.BigInteger(), nullable=True),
    sa.Column('limit_week', sa.BigInteger(), nullable=True),
    sa.Column('limit_month', sa.BigInteger(), nullable=True),
    sa.Column('utilization_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('window_5h_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updated_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(api_key_id IS NOT NULL AND ai_account_id IS NULL) OR (api_key_id IS NULL AND ai_account_id IS NOT NULL)', name='ck_resource_limit_state_one_asset'),
    sa.ForeignKeyConstraint(['ai_account_id'], ['ai_accounts.id'], ),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_account_id', name='uq_resource_limit_state_ai_account'),
    sa.UniqueConstraint('api_key_id', name='uq_resource_limit_state_api_key')
    )
    op.create_table('resource_usage_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=True),
    sa.Column('ai_account_id', sa.BigInteger(), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('event_source', sa.String(length=64), nullable=False),
    sa.Column('external_event_id', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(api_key_id IS NOT NULL AND ai_account_id IS NULL) OR (api_key_id IS NULL AND ai_account_id IS NOT NULL)', name='ck_resource_usage_event_one_asset'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ai_account_id'], ['ai_accounts.id'], ),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_source', 'external_event_id', name='uq_resource_usage_event_source_external')
    )
    op.create_index('ix_resource_usage_events_department_occurred_at', 'resource_usage_events', ['department_id', 'occurred_at'], unique=False)
    op.create_index('ix_resource_usage_events_occurred_at', 'resource_usage_events', ['occurred_at'], unique=False)
    op.create_table('usage_daily_summary',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=False),
    sa.Column('request_count', sa.BigInteger(), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('error_count', sa.BigInteger(), nullable=False),
    sa.Column('avg_latency_ms', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'user_id', 'department_id', 'project_id', 'provider_id', 'model_id', 'api_key_id', name='uq_usage_daily_summary_key')
    )
    op.create_table('assistant_messages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('redacted_content', sa.Text(), nullable=False),
    sa.Column('message_hash', sa.String(length=128), nullable=False),
    sa.Column('task_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('USER','ASSISTANT','SYSTEM')", name='ck_assistant_message_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assistant_messages_conversation_created_at', 'assistant_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_assistant_messages_trace_id', 'assistant_messages', ['trace_id'], unique=False)
    op.create_table('cost_ledger',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('usage_event_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('price_version_id', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('input_unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('output_unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('settled_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('ledger_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['price_version_id'], ['model_prices.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', name='uq_cost_ledger_request_id')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=False),
    sa.Column('price_version_id', sa.BigInteger(), nullable=False),
    sa.Column('request_type', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cached_input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('reasoning_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('prompt_hash', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['price_version_id'], ['model_prices.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('ix_usage_events_created_at', 'usage_events', ['created_at'], unique=False)
    op.create_index('ix_usage_events_user_created_at', 'usage_events', ['user_id', 'created_at'], unique=False)
    op.create_table('billing_reconciliation_issues',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('billing_import_id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('ledger_id', sa.BigInteger(), nullable=False),
    sa.Column('expected_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('delta_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['billing_import_id'], ['billing_imports.id'], ),
    sa.ForeignKeyConstraint(['ledger_id'], ['cost_ledger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_outputs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('usage_purpose_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('api_key_id', sa.BigInteger(), nullable=True),
    sa.Column('ai_account_id', sa.BigInteger(), nullable=True),
    sa.Column('cost_ledger_id', sa.BigInteger(), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('output_title', sa.String(length=255), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('value_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_user_id', sa.BigInteger(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED')", name='ck_work_output_status'),
    sa.CheckConstraint('(api_key_id IS NOT NULL AND ai_account_id IS NULL) OR (api_key_id IS NULL AND ai_account_id IS NOT NULL)', name='ck_work_output_one_asset'),
    sa.CheckConstraint('cost_usd >= 0', name='ck_work_output_cost_non_negative'),
    sa.CheckConstraint('total_tokens >= input_tokens + output_tokens', name='ck_work_output_total_tokens'),
    sa.CheckConstraint('value_usd >= 0', name='ck_work_output_value_non_negative'),
    sa.ForeignKeyConstraint(['ai_account_id'], ['ai_accounts.id'], ),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['cost_ledger_id'], ['cost_ledger.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['usage_purpose_id'], ['usage_purposes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_work_outputs_department_status_created_at', 'work_outputs', ['department_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_work_outputs_usage_purpose_id', 'work_outputs', ['usage_purpose_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_departments_manager_user_id_users', 'departments', type_='foreignkey')
    op.drop_index('ix_work_outputs_usage_purpose_id', table_name='work_outputs')
    op.drop_index('ix_work_outputs_department_status_created_at', table_name='work_outputs')
    op.drop_table('work_outputs')
    op.drop_table('billing_reconciliation_issues')
    op.drop_index('ix_usage_events_user_created_at', table_name='usage_events')
    op.drop_index('ix_usage_events_created_at', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_table('cost_ledger')
    op.drop_index('ix_assistant_messages_trace_id', table_name='assistant_messages')
    op.drop_index('ix_assistant_messages_conversation_created_at', table_name='assistant_messages')
    op.drop_table('assistant_messages')
    op.drop_table('usage_daily_summary')
    op.drop_index('ix_resource_usage_events_occurred_at', table_name='resource_usage_events')
    op.drop_index('ix_resource_usage_events_department_occurred_at', table_name='resource_usage_events')
    op.drop_table('resource_usage_events')
    op.drop_table('resource_limit_states')
    op.drop_table('project_budgets')
    op.drop_table('model_prices')
    op.drop_table('gateway_requests')
    op.drop_table('budget_reservations')
    op.drop_index('ix_assistant_conversations_user_last_message_at', table_name='assistant_conversations')
    op.drop_table('assistant_conversations')
    op.drop_table('asset_contracts')
    op.drop_table('approval_steps')
    op.drop_table('api_key_entitlements')
    op.drop_table('ai_account_assignments')
    op.drop_table('usage_purposes')
    op.drop_table('role_permissions')
    op.drop_table('projects')
    op.drop_table('models')
    op.drop_table('lava_task_bindings')
    op.drop_table('export_jobs')
    op.drop_table('billing_imports')
    op.drop_table('audit_logs')
    op.drop_table('approval_requests')
    op.drop_table('api_keys')
    op.drop_table('alerts')
    op.drop_table('ai_accounts')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('providers')
    op.drop_table('permissions')
    op.drop_table('lava_runtime_settings')
    op.drop_table('lava_connections')
    op.drop_table('departments')
    op.drop_table('alert_rules')
    op.drop_table('aggregation_jobs')
    # ### end Alembic commands ###
